### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by mcdowesj** [CinVerd/privateKeyCrack_example#1]
This is shit

**Comment by mcdowesj** [comment]
Please respond

**Comment by CinVerd** [comment]
With regards to your earlier, "helpful", comment, we here at CinVerd Software have the following response:
"Go fuck yourself you fucking fuck. Why don't you fuck off, and when you get there, fuck off again, and once again when you reach your destination, just fucking die, please. You fucking incompetent cunt. Fuck."
Thanks for helping make CinVerd Software even better! Have a nice day.
